# Site settings
site: WihaNotes
title: WihaNotes by Bagas Wihant
keywords: Bagas Wihant, Wihanotes
description: >-
  Bagas Wihant
lang: id-ID
timezone:  Asia/Jakarta
# repo: https://deaaprizal.github.io/log # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Bagas Wihantoro
  bio: Ngoding Dulu, Jagonya Belakangan
  logo: assets/images/bagas.png 
  github: iamwihant # github username
  twitter:  # twitter username
  facebook:  bagaswihant # facebook username
  instagram: iamwihant # instagram username
  # youtube: https://www.youtube.com/deaafrizal # youtube username
  linkedin:  # linkedin username
  email: bagaswihant@gmail.com # email adress


# URL settings
url: "https://iamwihant.github.io/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false